openapi: 3.0.3
info:
  title: Ascent Essentials - Backend API
  description: Documentation for Ascent Essentials backend
  version: 0.1.0
servers:
  - url: http://localhost/api/v1
tags:
  - name: product
    description: Operations related to products
paths:
  /products:
    get:
      tags:
        - product
      summary: Retrieve all products
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
  /product:
    post:
      tags:
        - product
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Product created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
  /product/{productId}:
    get:
      tags:
        - product
      summary: Retrieve a specific product
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
    put:
      tags:
        - product
      summary: Update a specific product
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '200':
          description: Product updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
    delete:
      tags:
        - product
      summary: Delete a specific product
      parameters:
        - name: productId
          in: path
          required: true
          description: ID of the product to delete
          schema:
            type: string
      responses:
        '204':
          description: Product deleted successfully
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: Not found
components:
  schemas:
    Category:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
        - name
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        category:
          $ref: '#/components/schemas/Category'
        status:
          type: string
          enum:
            - available
            - unavailable
        price:
          type: number
          format: float
        description:
          type: string
      required:
        - id
        - name
        - category
        - status
        - price
